version: '3.8'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: home-sec-mongo
    volumes:
      - data:/data
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    image: mongo
  mongo-express:
    ports:
      - '8081:8081'
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=home-sec-mongo
    image: mongo-express
volumes:
  data: {}
networks:
  default:
    name: mongodb_network
